<?php
/**
 * osCommerce Online Merchant
 * 
 * @copyright Copyright (c) 2013 osCommerce; http://www.oscommerce.com
 * @license GNU General Public License; http://www.oscommerce.com/gpllicense.txt
 */

define('HEADING_TITLE', 'Info');
define('NAVBAR_TITLE', 'Info');

define('NAVBAR_TITLE_SHIPPING', 'Shipping &amp; Returns');
define('HEADING_TITLE_SHIPPING', 'Shipping &amp; Returns');
define('INFO_SHIPPING', 'Put here your Shipping &amp; Returns information.');

define('NAVBAR_TITLE_PRIVACY', 'Privacy Notice');
define('HEADING_TITLE_PRIVACY', 'Privacy Notice');
define('INFO_PRIVACY', 'Put here your Privacy Notice information.');

define('NAVBAR_TITLE_CONDITIONS', 'Conditions of Use');
define('HEADING_TITLE_CONDITIONS', 'Conditions of Use');
define('INFO_CONDITIONS', 'Put here your Conditions of Use information.');

define('HEADING_TITLE_CONTACT', 'Contact');
define('NAVBAR_TITLE_CONTACT', 'Contact');
define('INFO_CONTACT_SUCCESS', 'Your enquiry has been successfully sent to the Store Owner.');
define('EMAIL_SUBJECT', 'Enquiry from ' . STORE_NAME);
define('ENTRY_NAME', 'Full Name:');
define('ENTRY_EMAIL', 'E-Mail Address:');
define('ENTRY_ENQUIRY', 'Enquiry:');
define('ERROR_ACTION_RECORDER', 'Error: An enquiry has already been sent. Please try again in %s minutes.');

define('NAVBAR_TITLE_COOKIE_USAGE', 'Cookie Usage');
define('HEADING_TITLE_COOKIE_USAGE', 'Cookie Usage');

define('TEXT_INFORMATION_COOKIE_USAGE', 'We have detected that your browser does not support cookies, or has set cookies to be disabled.<br /><br />To continue shopping online, we encourage you to enable cookies on your browser.<br /><br />For <strong>Internet Explorer</strong> browsers, please follow these instructions:<br /><ol><li>Click on the Tools menubar, and select Internet Options</li><li>Select the Security tab, and reset the security level to Medium</li></ol>We have taken this measurement of security for your benefit, and apologize upfront if any inconveniences are caused.<br /><br />Please contact the store owner if you have any questions relating to this requirement, or to continue purchasing products offline.');

define('BOX_INFORMATION_HEADING_COOKIE_USAGE', 'Cookie Privacy and Security');
define('BOX_INFORMATION_COOKIE_USAGE', 'Cookies must be enabled to purchase online on this store to embrace privacy and security related issues regarding your visit to this site.<br /><br />By enabling cookie support on your browser, the communication between you and this site is strengthened to be certain it is you who are making transactions on your own behalf, and to prevent leakage of your privacy information.');

define('NAVBAR_TITLE_SSL_CHECK', 'Security Check');
define('HEADING_TITLE_SSL_CHECK', 'Security Check');

define('TEXT_INFORMATION_SSL_CHECK', 'We have detected that your browser has generated a different SSL Session ID used throughout our secure pages.<br /><br />For security measures you will need to logon to your account again to continue shopping online.<br /><br />Some browsers such as Konqueror 3.1 does not have the capability of generating a secure SSL Session ID automatically which we require. If you use such a browser, we recommend switching to another browser such as <a href="http://www.microsoft.com/ie/" target="_blank">Microsoft Internet Explorer</a>, <a href="http://channels.netscape.com/ns/browsers/download_other.jsp" target="_blank">Netscape</a>, or <a href="http://www.mozilla.org/releases/" target="_blank">Mozilla</a>, to continue your online shopping experience.<br /><br />We have taken this measurement of security for your benefit, and apologize upfront if any inconveniences are caused.<br /><br />Please contact the store owner if you have any questions relating to this requirement, or to continue purchasing products offline.');

define('BOX_INFORMATION_HEADING_SSL_CHECK', 'Privacy and Security');
define('BOX_INFORMATION_SSL_CHECK', 'We validate the SSL Session ID automatically generated by your browser on every secure page request made to this server.<br /><br />This validation assures that it is you who is navigating on this site with your account and not somebody else.');
?>
